
services:
  app_example:
    build: ./app_example
    container_name: app_example
    ports:
      - "8002:8000"

  app:
    build: .
    container_name: authorization_app_example
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - db_data:/db/database
    ports:
      - "8000:8000"


  db:
    image: postgres:15
    container_name: postgres_db_example
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 5s
      retries: 5
      timeout: 3s


volumes:
  db_data:
